version: "3.8"

services:
  frontend:
    build: ./frontend/event-management
    volumes:
      - ./frontend/event-management:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:5000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - ngrok

  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/backend/uploads
      - ./backend/pdfs:/backend/pdfs
      - ./backend/assets:/backend/assets
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok
    command: http backend:5000
    environment:
      - NGROK_AUTHTOKEN=2nWnlou7c6TWCiPmvlabD7STo9S_5qUF9NaFkfkdrvCs4wV8K
    ports:
      - "4040:4040"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
