version: "3.8"

services:
  frontend:
    build: ./frontend/event-management
    volumes:
      - ./frontend/event-management:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
      - mongo
    # Remove the 'develop' section and rely on volumes for live syncing

  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/backend/uploads
      - ./backend/pdfs:/backend/pdfs
      - ./backend/assets:/backend/assets
      - ./backend:/backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    # Remove the 'develop' section and rely on volumes for live syncing

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
