version: "3.8"

services:
  frontend:
    build: ./frontend/event-management
    volumes:
      - ./frontend/event-management:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST= localhost
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
      - mongo

  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/backend/uploads
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
