version: "3.8"

services:
  frontend:
    build: ./frontend/event-management
    volumes:
      - ./frontend/event-management:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - REACT_APP_BACKEND_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - redis
      - mongo
    develop:
      watch:
        - action: sync
          path: ./frontend/event-management
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/event-management/package.json

  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/backend/uploads
      - ./backend/pdfs:/backend/pdfs
      - ./backend/assets:/backend/assets
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongo
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /backend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
